### ISSUE TITLE
User rank option no longer functions after forum update

### ISSUE THREAD

**Issue by RockSolid1106** [RockSolid1106/LTT-Sidebar-customizer#27]
**Describe the bug**
The option
"Show your level/rank in the profile dropdown"
no longer works. Only the text "USER MENU" is shown in the profile dropdown.

**To Reproduce**
1. Enable "Show your level/rank in the profile dropdown".
2. Go to the profile dropdown.

**Expected behavior**
The actual rank stats to appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/84492239/180778630-2841c2d3-080c-4be6-8fc6-abe10bf66c9d.png)

**Additional context**
This is a known issue after the forum update. This happens because the extension un-commented the code that displayed the stats, but now that piece of code has been removed.
I have found an alternative way to display those stats, which is by using the element that shows the stats in mobile view(what you get when you reduce the width of the page). I already have a working prototype for this and might push an update soon with some other minor bug fixes.
![image](https://user-images.githubusercontent.com/84492239/180781810-5409956c-eea3-4893-a5dc-0c9d24c561cc.png)

**Comment by EDKTech** [comment]
From the new forum update

**Comment by RockSolid1106** [comment]
Fixed in V0.9.2B #29
