### ISSUE TITLE
Configurator keeps changing size of window when profile menu is visited

### ISSUE THREAD

**Issue by realedk** [RockSolid1106/LTT-Sidebar-customizer#28]
**Describe the bug**
The screen jumps around as if the CSS is being executed and then in-executed.

**To Reproduce**
1. Go to the extension menu
2. Click on "Profile"
3. See error

**Expected behavior**
Smooth CSS operation

**Screenshots**
![Screenshot 2022-07-25 150116](https://user-images.githubusercontent.com/83384667/180864298-c3b2754a-0888-4e2b-b501-b3a13b2a5a33.png)

https://user-images.githubusercontent.com/83384667/180865307-8b4f1082-b687-4ce9-914b-648ad7e1cf68.mov

Happens on Windows Firefox only, it wasn't smooth but this exact thing didn't happen on macOS.
I think it is the mobile style rules interfering with the desktop style rules. As the video shows, when you shrink the browser window, the glitch does not occur

**Comment by RockSolid1106** [comment]
Thanks, I already had a report for this. You are right, it's the mobile CSS styling rules which I plan on removing altogether owing to the small number of users on mobile.

**Comment by realedk** [comment]
Confirmed this glitch does not happen on Chrome

**Comment by RockSolid1106** [comment]
Fixed in #29 V0.9.2B, should be available in the various webstores as soon as Edge approves my addon. I have no idea why they take a week to approve while Chrome and Firefox take barely a few hours.
Once that is shipped, please test if this occurs still.

**Comment by RockSolid1106** [comment]
@EDKTech please can you check if this still occurs in the new version? I have now published it on all webstores.

**Comment by RockSolid1106** [comment]
In communications with EDK on another platform, he has told me that the issue has been resolved with 0.9.2B.
